### ISSUE TITLE
 Relation reference widget - filter lists are not refreshed in attribute table form view

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#190] opened 2017-06-01 10:10 UTC
I create this issue on QWAT github to not forget this report bug on QGIS. 
bug report QGIS : [https://issues.qgis.org/issues/16400](https://issues.qgis.org/issues/16400)

**Comment by dsavary** [comment] 2017-06-01 10:10
For Lausanne, it's important in order to work with QWAT in production.
@haubourg , will this bug be fixed for QGIS 2.xx LTR ? or QGIS 3.0 ?
Can we put this issue on top priority for QWAT team ?

**Comment by haubourg** [comment] 2017-06-01 13:15
Yes, the whole package with the qgis issues you raised about forms is planned for june/july

**Comment by pblottiere** [comment] 2017-08-18 07:28
I created a PR to fix this issue : https://github.com/qgis/QGIS/pull/5043

**Comment by pblottiere** [comment] 2017-08-18 14:41
PR is merged, I'm doing the backport

**Comment by pblottiere** [comment] 2017-08-18 15:31
Backport : https://github.com/qgis/QGIS/pull/5045

**Comment by pblottiere** [comment] 2017-08-21 07:56
Backport is merged

**Comment by dsavary** [comment] 2017-08-28 12:06
Tested with QGIS 2.18.12. It works well, but only with no null value.
If one row in the table have a null value, the filter lists are not correctly refreshed and keep the previous value. GIF example : 

![refresh_reference_value_when_null](https://user-images.githubusercontent.com/6229296/29772623-ec48255a-8bf9-11e7-913d-0c7da2cb7b39.gif).

**Comment by pblottiere** [comment] 2017-10-02 14:25
@dsavary Do you agree with the next behavior ?

![optimised](https://user-images.githubusercontent.com/9266424/31082060-ba6340ae-a785-11e7-90b3-0e387e3ef3bd.gif)

**Comment by dsavary** [comment] 2017-10-02 15:59
@pblottiere yes! It seems to be good. 
The feature 4 has no value if I understand well:) 
The behavior is the same when you open only a form ?

**Comment by pblottiere** [comment] 2017-10-03 08:34
> The feature 4 has no value if I understand well

Yes, like in your GIF example.

> The behavior is the same when you open only a form ?

Yes

**Comment by pblottiere** [comment] 2017-10-03 12:12
A PR is in progress.

**Comment by haubourg** [comment] 2017-10-17 08:37
PR is https://github.com/qgis/QGIS/pull/5350

**Comment by dsavary** [comment] 2017-10-24 08:09
tested with QGIS 2.18
If you choose the "null" value in the list, it works well. :+1: 
But, strange behaviour : 

- if you deleted the value with the keyboard, the "not null" constraint is not respected
- if you don't choose any value in the "filter" lists, the attribute value is replaced by the first value found in the list. (in the demo example, it take 11). strange ?
It would be better that it put the null value or keep the current value.

![referenced_value_list](https://user-images.githubusercontent.com/6229296/31931333-2a434ba2-b8a3-11e7-8c01-a859ef899234.gif)

**Comment by pblottiere** [comment] 2017-11-30 13:13
Hi @dsavary!

> if you deleted the value with the keyboard, the "not null" constraint is not respected

Indeed, you're right. It's fixed, I just have to write a PR.

> if you don't choose any value in the "filter" lists, the attribute value is replaced by the first value found in the list. (in the demo example, it take 11). strange ?

What do you think about setting the first element of the list each time the filter is updated? With your example, as soon as you select *Material value* in the first filtering combobox, *NULL* will be selected (and a message will be raised about an invalid constraint).

@haubourg I would be glad to hear your opinion on this too if you have a moment.

**Comment by pblottiere** [comment] 2017-11-30 17:30
> > if you deleted the value with the keyboard, the "not null" constraint is not respected

> Indeed, you're right. It's fixed, I just have to write a PR.

The PR is https://github.com/qgis/QGIS/pull/5775

**Comment by pblottiere** [comment] 2017-12-05 15:05
PR about setting a NULL key when the value is deleted from the keyboard is merged for 2.18.

But I need some answers about my questions on the "filter" lists to continue :). Let me know.

**Comment by dsavary** [comment] 2017-12-06 15:24
I think:
Each time, the user change the filter, the first "matching" element of the list is selected. 

- If you choose a existing material value (for example "l'acier", the first matching value will be selected.
- If you choose no value in the filter like "material value"  in example, NULL will be selected.

**Comment by pblottiere** [comment] 2017-12-06 15:57
> Each time, the user change the filter, the first "matching" element of the list is selected. 

> - If you choose a existing material value (for example "l'acier", the first matching value will be selected.
> - If you choose no value in the filter like "material value"  in example, NULL will be selected.  

OK, I'm going to do that. Thank you for your input @dsavary :+1:!

**Comment by pblottiere** [comment] 2017-12-15 10:42
> if you don't choose any value in the "filter" lists, the attribute value is replaced by the first value found in the list. (in the demo example, it take 11). strange ?
> It would be better that it put the null value or keep the current value.

Hi @dsavary,

This PR  https://github.com/qgis/QGIS/pull/5879 should fixed your issue.

**Comment by pblottiere** [comment] 2017-12-18 08:42
PR is merged.

**Comment by dsavary** [comment] 2018-04-11 13:37
Tested with QGIS 2.18.18 -> OK 
Tested with last QGIS 3.0 dev : -> KO
If the user change one of the "chain filters" the corresponding value is not automatically refresh, the last value keep unchanged. ( input error in database...). The user must select the correct value. 
See the gif
![referenced_value_list_mot_refresh](https://user-images.githubusercontent.com/6229296/38620127-3d2c9e70-3d8d-11e8-85e6-bf1c9ccc20a4.gif)

**Comment by haubourg** [comment] 2018-04-12 07:24
@pblottiere nasty issue, do you think tests are doable for this feature?

**Comment by pblottiere** [comment] 2018-04-12 07:32
> Tested with last QGIS 3.0 dev : -> KO

I think that the underlying widget has been redesigned in QGIS 3.0. I'll take a look to fix that.

**Comment by ponceta** [comment] 2020-12-24 06:56
Regression on QGIS 3.X.X Seems to be fixed, I close this. Please feel free to open a new issue in QGIS if any relational widget encounters any trouble.

**Closed by ponceta** 2020-12-24 06:56 UTC
Labels: 4 - Done, Bug, P1, QGIS Core
