### ISSUE TITLE
QWAT on QGIS 3.4.X

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#181] opened 2017-04-12 06:43 UTC
Hi,

I propose to add here all the points which are problematic towards a migration to QGIS 3.0 (actual 2.99) from existing project to project in v 3.0.

 - [x] Symbology, labeling : anything expression based is broken due to boolean handling on Postgres see _dirty hack_
 - [x] Legend : z order is not respected (@wonder-sk)
 - [x] Map composers: it seems atlas generation config is lost (@nyalldawson)

Feel free to edit my post and add your points to this list.

 - [x] Import de données GPS (actuellement via plugin)
 - [x] Barre de recherche QGIS (plugin quickfinder)-> Replaced by Navigator and geomapfish Locator

**Comment by ponceta** [comment] 2017-04-12 06:54
![image](https://cloud.githubusercontent.com/assets/8614223/24944560/11d8f91c-1f5c-11e7-9cd2-66db99093eb8.png)

For Pully, forms are correctly transfered, simple styles too, conditionnal styles are not (have to investigate why), edition works, composers seems to be ok except for conditionnal styles.

+ For users :
Ajout du copier déplacer
![image](https://cloud.githubusercontent.com/assets/8614223/24944736/ad3f5158-1f5c-11e7-97e9-bb25856c1f98.png)

Ajout du snapping rapide
![image](https://cloud.githubusercontent.com/assets/8614223/24944912/6bb4d392-1f5d-11e7-947e-dc47e1fd2315.png)

Interface sensiblement identique (pas de grands changements côté interface)

**Comment by haubourg** [comment] 2017-04-13 09:50
To me it's still a bit early to start this work ,but raising the issues on conditionnal style to QGIS dev's can be usefull.

**Comment by 3nids** [comment] 2017-09-04 09:22
expressions having conditions on boolean for PG layers are broken.
see https://github.com/qgis/QGIS/commit/cfb8552b14 and its comment

**Comment by 3nids** [comment] 2017-09-04 09:28
quick dirty hack   
`sed -r "s/'t'/true/g; s/'f'/false/g" qwat.qgs > qwat_qgis3.qgs`

**Comment by 3nids** [comment] 2017-09-04 09:39
@wonder-sk do you know why layer order is not respected when opening a 2.x project on QGIS 3? eay fix?

**Comment by 3nids** [comment] 2017-09-04 09:47
@nyalldawson is it expected that atlas generation config is lost when opening 2.x project on QGIS 3?

**Comment by m-kuhn** [comment] 2017-09-04 12:54
I guess your "quick and dirty" hack is the way to go. I can't think of anything better.

**Comment by 3nids** [comment] 2017-09-04 13:04
@m-kuhn thanks for the feed-back.

**Comment by wonder-sk** [comment] 2017-09-06 11:04
Haven't seen the issue (maybe just haven't tried) - please feel free to file a bug report in QGIS tracker for that...

**Comment by ponceta** [comment] 2017-09-13 16:22
@haubourg this is now a milestone for End 2018!

**Comment by tudorbarascu** [comment] 2018-02-07 09:13
I just noticed that if I create a feature in a Linestring layer with snap on the 3d node, the new line has 3D and cannot be saved (I have to toggle off the nodes layer in order to create the line with snap on the pipe nodes). Is there a way to deactivate this behavior? Linestrings shouldn't become LinestringZ..

**Comment by haubourg** [comment] 2018-02-07 09:37
@lbartoletti @pblottiere Hi guys, I had no time to test you Z branch improvements yet. Does it adress Tudor's issue ?

**Comment by pblottiere** [comment] 2018-02-07 12:49
> I just noticed that if I create a feature in a Linestring layer with snap on the 3d node, the new line has 3D and cannot be saved (I have to toggle off the nodes layer in order to create the line with snap on the pipe nodes). Is there a way to deactivate this behavior? Linestrings shouldn't become LinestringZ..

Hi @tudorbarascu!

I tried to reproduce your issue on master but I didn't succeed in. But I probably missed something...

Here are my steps:
1. create a LineStringZ layer
2. add a new 3D feature in LineStringZ layer and save
3. create a LineString layer
4. add a new 2D LineString feature by snapping on some points of the LineStringZ feature 
5. no issue during the saving of the 2D feature (which is still a **2D** feature)

Can you give me some more information? I'll try to reproduce.

Thank you!

**Comment by tudorbarascu** [comment] 2018-02-08 04:38
@pblottiere Sure! Thanks for looking. The problem I described is when snapping on PointZ (nodes in our case) not on LinestringZ. To replicate, you need a PointZ and a Linestring layer. Draw a Linestring that snaps to any PointZ feature and try to save.

Test tables:

```
CREATE TABLE test_point (id serial PRIMARY KEY, name text, geom geometry(PointZ, 3844) );
CREATE TABLE test_line (id serial PRIMARY KEY, name text, geom geometry(Linestring, 3844) );
```

At first I created the test tables without the ``name text`` column but it seems I found a regression as QGIS doesn't show the SAVE button when just the id and geom columns although it lets me to add points and lines.

**Comment by 3nids** [comment] 2018-02-12 11:27
Quickfinder will gets integrated in core in 3.2 for the services part (geomapfish, osm).

**Comment by pblottiere** [comment] 2018-02-13 14:57
@tudorbarascu Oh! I tried and I just got a segfault during saving... I'll take a look!

**Comment by pblottiere** [comment] 2018-02-13 15:00
@tudorbarascu I tried with my branch coming with this PR https://github.com/qgis/QGIS/pull/5823 and there's no more segfault. Moreover, I successfully saved the linestring layer.

I'll let you know once this PR is merged!

**Comment by tudorbarascu** [comment] 2018-02-18 14:25
@pblottiere Noticed the PR was merged 3 hours ago.
I just built and tested and the problem is still present.
Thanks for your very nice work.

**Comment by pblottiere** [comment] 2018-02-18 19:55
> I just built and tested and the problem is still present.

@tudorbarascu Damn :(! It means that I didn't reproduce your issue correctly... I'll try again tomorrow and I let you know.

**Comment by tudorbarascu** [comment] 2018-04-09 09:39
@pblottiere I added a gif so that you can reproduce more easily.

* Create the tables
```
CREATE TABLE test_point (id serial PRIMARY KEY, name text, geom geometry(PointZ, 3844) );
CREATE TABLE test_line (id serial PRIMARY KEY, name text, geom geometry(Linestring, 3844) );
```
* Add a point then save

* Add a line starting from the point with snapping.

![bug](https://user-images.githubusercontent.com/3179646/38490899-0786f694-3bf3-11e8-9fd3-73f82b7d981a.gif)

**Comment by haubourg** [comment] 2018-04-09 09:58
@tudorbarascu Can you show the log panel with the error messages raised by PostGIS?

**Comment by tudorbarascu** [comment] 2018-04-09 10:27
@haubourg Sure, updated comment. I thought I had already posted it above. My bad ;).

**Comment by pblottiere** [comment] 2018-04-23 15:05
@tudorbarascu  

> I added a gif so that you can reproduce more easily.

Oh yes, indeed! Thanks for the GIF, I'm able to reproduce now! I take a look.

**Comment by tudorbarascu** [comment] 2018-07-04 07:37
Trying to migrate to 3. On master, if I add the pipe layer the NOT NULL constraints of the ``fk_node_a`` and ``node_b`` columns propagate to the dialog thus disabling the ``OK`` of the dialog. As these columns get filled by db triggers it's an impediment.
Is there a workaround?

**Comment by tudorbarascu** [comment] 2018-11-15 13:03
Issue with workaround here: https://issues.qgis.org/issues/19671

**Comment by tudorbarascu** [comment] 2018-11-15 13:37
@haubourg Sorry, from that issue you are taken to another etc. and then you see the solution. I updated the original issue with: ``A workaround would be to simply fill those specific columns with a default value, -1 let's say and it will let you pass while the database logic will change it to what's supposed to be.``

**Comment by haubourg** [comment] 2018-11-15 14:47
@tudorbarascu Nice ! thanks for making it clearer !

**Comment by ponceta** [comment] 2018-11-27 13:53
> @m-kuhn expressions having conditions on boolean for PG layers are broken.
> see [qgis/QGIS@cfb8552](https://github.com/qgis/QGIS/commit/cfb8552b14) and its comment
> 
> quick dirty hack
> `sed -r "s/'t'/true/g; s/'f'/false/g" qwat.qgs > qwat_qgis3.qgs`

On notepad++ 
CTRL+H
replace 't'
by true

**Closed** 2019-07-11 12:44 UTC
Labels: 2 - Work started, Enhancement
