### ISSUE TITLE
Important bug on  reshape tool - QGIS 2.18.12

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#221] opened 2017-09-10 17:52 UTC
You can extend a 3d line with the reshape tool (remodeler une entité) by snapping on endpoints. But, when you extend a 3d line by snapping on the end vertex of the line, the 3d new vertex take the value "Nan" , not very good but ok. It would be better 0 ...
However, when you extend a 3d line by snapping on the start vertex of the line, we cann't see the Z coordinate with node tool ?? and the worst after saving the feature, every vertex take 0 at the z coordinate ?? 
Is it possible to fix this bug as soon as possible for QGIS 2.18 ?
Demo Gif : https://share.oslandia.net/public/f19e52

**Comment by haubourg** [comment] 2017-09-11 07:48
Hi Daniel, 
- **extends with reshape tool adds nan values to Z:** I confirm that, but that's not a bad behavior in 2.18 context since all we did with default z values fell in 2.99 only. 0 is not better as all discussions with core dev's led to dealing with Nan in QGIS and not 0 for no value (was planned but rejected by NextGIS). This map tool may be the only one to behave correctly in fact. 


- Converting to 0 and seeing a "r" column in node tool editor as seen in your gif doesn't happen to me with a Geopackage dataset. What datasource format are you using ?

**Comment by dsavary** [comment] 2017-09-11 08:26
Hi Regis,

- Ok for the first point.
- Tested with datasource format SHP and POSTGIS

**Comment by haubourg** [comment] 2017-09-11 08:45
Tested with shp and confirmed, all z and m are reset by reshape tool. Strange that this is provider dependant. I'll look into redmine to seek for similar issues

**Comment by haubourg** [comment] 2017-09-11 08:52
Ticket filed here : https://issues.qgis.org/issues/17118

**Comment by haubourg** [comment] 2017-09-11 08:53
@dsavary Do you think it is a regression? I never tested that before.

**Comment by dsavary** [comment] 2017-09-11 09:01
@haubourg I don't know. I also never tested that before. 
Do you think that this bug can be still fix for QGIS 2.18 ?

**Comment by haubourg** [comment] 2017-09-11 10:10
2.18 has a point release every month until 3.2 becomes LTR, so yes. 
2.18.13 will be packed within a week and we don't have enough ressources for that. (Paul is in vacation)
The the main effort will be put into 3.0 feature and fixes. For 2.18.14 to be released mid october, I think we can make it, but we can't evaluate the cost before trying to fix it.

**Comment by dsavary** [comment] 2017-09-11 11:34
Ok for 2.18.14 . I think that the QWAT group can pay to fix this. :) ?
A good tool to extend a 3d line is very important to manage a network...
Or Perhaps, we can do a plugin "extend a 3d line with snapping points"

**Comment by ponceta** [comment] 2017-09-28 11:53
As said by PSC on monday 25.09.2017, this is considered as bug and should be fixed asap.

**Comment by ponceta** [comment] 2017-09-28 12:27
![reshape_tool](https://user-images.githubusercontent.com/8614223/30966211-7691d3ac-a458-11e7-863e-80c3362aacf6.gif)

NaN for newly created vertex is fine but losing existing Z value on node is a pity.

Tested on qwat pipe layer on postgres.

**Comment by haubourg** [comment] 2017-10-04 16:10
@pblottiere if you have some time left, can you try to fix that? Please assign yourself to this ticket and in https://issues.qgis.org/issues/17118

**Comment by haubourg** [comment] 2017-10-11 13:50
fixed in master QGIS3
Backport in 2.18 started

**Comment by pblottiere** [comment] 2017-10-16 08:34
PR is merged is 2.18 : https://github.com/qgis/QGIS/pull/5349. 

Let me know!

**Comment by haubourg** [comment] 2017-10-18 16:29
@savary can you test if release nightlies are good to you?

**Comment by savary** [comment] 2017-10-18 20:54
I think I was added to this post by mistake. Don't you mean someone else?

**Comment by haubourg** [comment] 2017-10-19 06:25
@savary, sorry yes, I meant to ping @ponceta.
But your tests are welcome too.

**Comment by dsavary** [comment] 2017-10-19 06:36
@haubourg my profile name is @dsavary and not "savary" . Sorry :)

**Comment by haubourg** [comment] 2017-11-24 08:26
@Paul, could you throw an eye on the last issue found by @dsavary  ?

**Comment by haubourg** [comment] 2017-12-01 12:44
PR for master here https://github.com/qgis/QGIS/pull/5780

**Comment by pblottiere** [comment] 2017-12-01 13:35
I'm waiting for a review before doing the backport.

**Comment by pblottiere** [comment] 2017-12-06 12:12
PR for master has been merged. I'm working on the backport now.

**Comment by dsavary** [comment] 2017-12-06 15:26
Good news thanks. 
Tell me when I can test.

**Comment by dsavary** [comment] 2017-12-14 10:18
This bug fix is included in the last QGIS version 2.18.15 ?

**Comment by pblottiere** [comment] 2017-12-14 20:03
> This bug fix is included in the last QGIS version 2.18.15 ?

Not yet, I just made the backport.

**Comment by pblottiere** [comment] 2017-12-18 08:42
Backport is merged.

**Comment by dsavary** [comment] 2018-03-05 11:00
tested with 2.18.16  , ok .
We can close this issue :) 
Thanks Paul

**Closed** 2018-03-05 14:17 UTC
Labels: 4 - Done, Bug, P1, QGIS Core
